### ISSUE TITLE
Not Working.

### ISSUE THREAD

**Issue by AnshulKale08** [qertyuiop12345678/Logiffy#15]
So I did all my best but it gives me errors after errors. I do not know if it is really not working or what but I would like you to make a video tutorial on it so that we can see how it works. 

Please see my request and also can you give your discord username as you have said add me on discord but you havent given your name. 
If not then please add me 😈iamnotamerican9😈#8487

**Comment by qertyuiop12345678** [comment]
I also put my discord server link there, now.

**Comment by timof121** [comment]
> I also put my discord server link there, now.

whats ur discord name in the server

**Comment by AnshulKale08** [comment]
> I also put my discord server link there, now.

It says expired
