### ISSUE TITLE
Connection failed: ProxySQL Error

### ISSUE THREAD

**Issue by ignBane** [qertyuiop12345678/Logiffy#2]
When I generate JSCode this is the code:
```Connection failed: ProxySQL Error: Access denied for user ''@'2a02:4780:bad:f00d::f' (using password: NO)```

**Comment by qertyuiop12345678** [comment]
It works for me. Check your SQL, also I have stopped maintaining it, so I need someone to.

**Comment by ignBane** [comment]
It work's now :)

**Comment by timof121** [comment]
I have this problem too

**Comment by qertyuiop12345678** [comment]
Im going to update this like today.
