### ISSUE TITLE
000webhost gives me error

### ISSUE THREAD

**Issue by BlackHoleBomb** [qertyuiop12345678/Logiffy#6]
I saw the other issue where you told the person to give SQL details, but I don't know how SQL has to do with this.
I put all the files into public-html and it gives me an error.

I don't know much about Javascript and HTML 

I know this isn't an issue but I have no idea how to fix it...

**Comment by catastrofi9** [comment]
Atleast explain ur error

**Comment by BlackHoleBomb** [comment]
> Atleast explain ur error

Okay? It doesn't give me an actual error. When I launch the 000webhost website I created, I entered the webhook and prompt, I clicked generate and it popped up with a box that said "Error! Please retry.".

![ikCapture](https://user-images.githubusercontent.com/79602613/109363450-99f08a80-785a-11eb-9f96-15747d25176c.PNG)

**Comment by qertyuiop12345678** [comment]
Answered here : https://github.com/qertyuiop12345678/Logiffy/issues/8
